# This is a basic workflow to help you get started with Actions

name: CI

# Controls when the workflow will run
on:
  # Triggers the workflow on push or pull request events but only for the headless branch
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build:
    # The type of runner that the job will run on
    runs-on: windows-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v2

      # Runs a single command using the runners shell
      - name: Install NPM Dependencies
        run: npm install
        
      - name: Set up NASM
        # You may pin to the exact commit or the version.
        # uses: ilammy/setup-nasm@9a15c8cb72fe84e3e00527b3014de04693cf60cf
        uses: ilammy/setup-nasm@v1.2.0
        with:
          # NASM version to install
          version: 2.15.05
          platform: win64
          
      - name: setup-msbuild
        uses: microsoft/setup-msbuild@v1
        
      - name: Visual Studio shell
        # You may pin to the exact commit or the version.
        # uses: egor-tensin/vs-shell@2cef0a902be6c2434178a0d0e4d83ae07a9dd0e0
        uses: egor-tensin/vs-shell@v2
        with:
          # Target architecture
          arch: x64
        
      # Runs a set of commands using the runners shell
      - name: Run Build Script
        run: npm run build
        
      - name: Upload a Build Artifact
        uses: actions/upload-artifact@v2.2.4
        with:
          # Artifact name
          name: InsomniaClient
          # A file, directory or wildcard pattern that describes what to upload
          path: ./InsomniaClient.exe
